export enum ServiceRequestStatus {
  SOLICITADO = 'SOLICITADO',
  CANCELADO = 'CANCELADO',
  AGENDADO = 'AGENDADO',
  RECIBIDO = 'RECIBIDO',
  EN_PROCESO = 'EN_PROCESO',
  ESPERANDO_PIEZA = 'ESPERANDO_PIEZA',
  LISTO_PARA_ENTREGA = 'LISTO_PARA_ENTREGA',
  ENTREGADO = 'ENTREGADO',
  EN_GARANTIA = 'EN_GARANTIA',
  RESUELTO = 'RESUELTO',
  CERRADO = 'CERRADO',
}
